<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('van der Sangen =)')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-datepicker.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->appendFile($this->basePath('js/bootstrap-datepicker.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))                
                ->appendFile($this->basePath('js/javascript.js'))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img class="img-circle img" src="<?php echo $this->basePath('img/nav-logo.png') ?>" alt="Nav logo"/>
                        &nbsp;<?php echo $this->translate('Van der Sangen') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('home/default', ['action' => 'lars']) ?>"><?php echo $this->translate('Lars') ?></a></li>
                        <li><a href="<?php echo $this->url('home/default', ['action' => 'patty']) ?>"><?php echo $this->translate('Patty') ?></a></li>
                        <li><a href="<?php echo $this->url('home/default', ['action' => 'lammie']) ?>"><?php echo $this->translate('Lammie') ?></a></li>
                        <li><a href="<?php echo $this->url('home/default', ['action' => 'betsie']) ?>"><?php echo $this->translate('Betsie') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div id="content">
                <?php echo $this->content; ?>
            </div>

            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Lars van der Sangen. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
