<h3><?= $this->translate('Persons') ?></h3>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="col-xs-2 col-md-2 col-lg-2"></th>
            <th class="col-xs-4 col-md-4 col-lg-4"><?= $this->translate('Name') ?></th>
            <th class="col-xs-4 col-md-4 col-lg-4"><?= $this->translate('Birthdate') ?></th>
            <th class="col-xs-2 col-md-2 col-lg-2"><?= $this->translate('#') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        /* @var $person Application\Entity\Person */
        foreach ($personCollection as $person)
        {
            ?>
            <tr>
                <td class="col-xs-2 col-md-2 col-lg-2 text-center">
                    <?= $this->personIcon($person, $fileService) ?>
                </td>
                <td class="col-xs-4 col-md-4 col-lg-4">
                    <?= $person->parseFullname() ?>
                </td>
                <td class="col-xs-4 col-md-4 col-lg-4">
                    <?= $person->getBirthdate()->format('d-m-Y') ?>
                </td>
                <td class="col-xs-2 col-md-2 col-lg-2">
                    <a class="btn btn-sm btn-primary"
                       href="<?= $this->url('admin/person/edit', [ 'personId' => $person->getPersonId() ]) ?>" >
                        <i class="fa fa-edit"></i>
                        <?= $this->translate('Edit') ?>
                    </a>

                    <a class="btn btn-sm btn-danger"
                       href="<?= $this->url('admin/person/delete', ['personId' => $person->getPersonId()]) ?>">
                        <i class="fa fa-trash-o"></i>
                        <?= $this->translate('Delete') ?>
                    </a>

                </td>
            </tr>            
            <?php
        }
        ?>

    </tbody>        
</table>
