<div class="row">
    <div class='col-xs-12 col-sm-12 col-md-6'>
        <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->lars, 'fileService' => $this->fileService]) ?>
    </div>

    <div class='col-xs-12 col-sm-12 col-md-6'>
        <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->patty, 'fileService' => $this->fileService]) ?>
    </div>

    <div class='col-xs-12 col-sm-12 col-md-6'>
        <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->lammie, 'fileService' => $this->fileService]) ?>
    </div>

    <div class='col-xs-12 col-sm-12 col-md-6'>
        <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->betsie, 'fileService' => $this->fileService]) ?>
    </div>
</div>
