<div class="row">
    <div class='col-xs-12 col-sm-12 col-md-6'>
    <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->lars]) ?>
</div>

<div class='col-xs-12 col-sm-12 col-md-6'>
    <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->patty]) ?>
</div>

<div class='col-xs-12 col-sm-12 col-md-6'>
    <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->lammie]) ?>
</div>

<div class='col-xs-12 col-sm-12 col-md-6'>
    <?= $this->partial('application/person/partial/infotable.phtml', ['person' => $this->betsie]) ?>
</div>
</div>
